const data = {
    objects: [
        {
            id: '7y0y',
            name: '엔트리봇',
            script:
                '[[{"id":"jer1","x":16,"y":104,"type":"mouse_clicked","params":[null],"statements":[],"movable":null,"deletable":1,"emphasized":false,"readOnly":null,"copyable":true,"assemble":true,"extensions":[]},{"id":"l19r","x":0,"y":0,"type":"show","params":[null],"statements":[],"movable":null,"deletable":1,"emphasized":false,"readOnly":null,"copyable":true,"assemble":true,"extensions":[]}]]',
            objectType: 'sprite',
            rotateMethod: 'free',
            scene: '7dwq',
            sprite: {
                pictures: [
                    {
                        id: 'vx80',
                        dimension: { width: 144, height: 246 },
                        fileurl: '/lib/entry-js/images/media/entrybot1.svg',
                        name: '엔트리봇_걷기1',
                        imageType: 'svg',
                    },
                    {
                        id: '4t48',
                        dimension: { width: 144, height: 246 },
                        fileurl: '/lib/entry-js/images/media/entrybot2.svg',
                        name: '엔트리봇_걷기2',
                        imageType: 'svg',
                    },
                ],
                sounds: [
                    {
                        duration: 1.3,
                        ext: '.mp3',
                        id: '8el5',
                        fileurl: '/lib/entry-js/images/media/bark.mp3',
                        name: '강아지 짖는 소리',
                    },
                ],
            },
            selectedPictureId: 'vx80',
            lock: false,
            entity: {
                x: 0,
                y: 0,
                regX: 72,
                regY: 123,
                scaleX: 0.5128205128205128,
                scaleY: 0.5128205128205128,
                rotation: 0,
                direction: 90,
                width: 144,
                height: 246,
                font: 'undefinedpx ',
                visible: true,
            },
        },
    ],
    scenes: [{ id: '7dwq', name: '장면 1' }],
    variables: [
        {
            name: '초시계',
            id: 'brih',
            visible: false,
            value: '0',
            variableType: 'timer',
            isCloud: false,
            isRealTime: false,
            cloudDate: false,
            object: null,
            x: 134,
            y: -70,
        },
        {
            name: ' 대답 ',
            id: '1vu8',
            visible: false,
            value: '0',
            variableType: 'answer',
            isCloud: false,
            isRealTime: false,
            cloudDate: false,
            object: null,
            x: 150,
            y: -100,
        },
    ],
    messages: [],
    functions: [],
    tables: [],
    speed: 60,
    interface: { menuWidth: 332, canvasWidth: 480, object: '7y0y' },
    expansionBlocks: [],
    aiUtilizeBlocks: [],
    hardwareLiteBlocks: [],
    externalModules: [],
    externalModulesLite: [],
};
